version: '3.7'
services:
  flaskend:
    hostname: flask-frontend
    container_name: tiered-flaskend
    build: ./flaskend
    depends_on:
      - api
    ports:
      - 9123:9123
    volumes:
      - .:/usr/src/application
    environment:
      - WEB_HOST=0.0.0.0
      - WEB_PORT=9123
    networks:
      - tiered
  djangoend:
    hostname: django-frontend
    container_name: tiered-djangoend
    build: ./djangoend
    depends_on:
      - api
    ports:
      - 9124:9124
    volumes:
      - .:/usr/src/application
    environment:
      - WEB_HOST=0.0.0.0
      - WEB_PORT=9124
    networks:
      - tiered
  api:
    hostname: backend
    container_name: tiered-backend
    build: ./backend
    depends_on:
      - mongodb
    ports:
      - 9125:9125
    volumes:
      - .:/usr/src/application
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=9125
      - DB=mongodb://mongodb:27017/tieredapp
    networks:
      - tiered
  mongodb:
    hostname: database
    container_name: tiered-database
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/usr/data/db
    command: mongod --smallfiles --logpath=/dev/null
    networks:
      - tiered
networks:
  tiered: