version: '3.2'
services:
  web:
    build: .
    ports:
     - 9123:9123
    volumes:
     - .:/usr/src/application
    environment:
     - ENV=development
     - WEB_HOST=0.0.0.0
     - WEB_PORT=9123