version: '3.7'
services:
  flask-web:
    hostname: flask-frontend
    container_name: tiered-flask-frontend
    build: ./flask
    depends_on:
      - api
    ports:
      - 9123:9123
    volumes:
      - .:/usr/src/application
    environment:
      - ENV=development
      - WEB_HOST=0.0.0.0
      - WEB_PORT=9123
    networks:
      - tiered
  angular-web:
    hostname: angular-frontend
    container_name: tiered-angular-frontend
    build: ./angular
    depends_on:
      - api
    ports:
      - 9124:9124
    volumes:
      - .:/usr/src/application
    environment:
      - ENV=development
      - WEB_HOST=0.0.0.0
      - WEB_PORT=9124
    networks:
      - tiered
  api:
    hostname: backend
    container_name: tiered-sdv701-backend
    build: ./backend
    depends_on:
      - mongodb
    ports:
      - 9125:9125
    volumes:
      - .:/usr/src/application
    environment:
      - ENV=development
      - API_HOST=0.0.0.0
      - API_PORT=9125
      - DB=mongodb://mongodb:27017/tieredapp
    networks:
      - tiered
  mongodb:
    hostname: database
    container_name: tiered-sdv701-database
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/usr/data/db
    command: mongod --smallfiles --logpath=/dev/null
    networks:
      - tiered
networks:
  tiered: